# Cleaning

In [1]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report

In [7]:
DATA_PATH = "../data/raw/Loan_Default.csv"   # change path if needed
df = pd.read_csv(DATA_PATH)
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [8]:
df=df.drop_duplicates()

num_cols=df.select_dtypes(include=['int64','float64']).columns
df[num_cols]=df[num_cols].fillna(df[num_cols].median())

cat_cols=df.select_dtypes(include=['object']).columns
df[cat_cols]=df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [10]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

In [11]:
x=df.drop("Default", axis=1)
y=df["Default"]

In [12]:
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
print(x_train.dtypes)

LoanID             object
Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education          object
EmploymentType     object
MaritalStatus      object
HasMortgage        object
HasDependents      object
LoanPurpose        object
HasCoSigner        object
dtype: object

In [42]:
x_train = x_train.drop(columns=['LoanID'])
x_test  = x_test.drop(columns=['LoanID'])

In [50]:
cat_cols = x_train.select_dtypes(include='object').columns

x_train = pd.get_dummies(x_train, columns=cat_cols, drop_first=True)
x_test  = pd.get_dummies(x_test, columns=cat_cols, drop_first=True)

# align train & test columns
x_train, x_test = x_train.align(x_test, join='left', axis=1, fill_value=0)

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test  = scaler.transform(x_test)

In [52]:
log_reg = LogisticRegression(max_iter=1000,class_weight='balanced')
log_reg.fit(x_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [53]:
y_pred = log_reg.predict(x_test)
y_pred_prob = log_reg.predict_proba(x_test)[:,1]

y_pred_custom=(y_pred_prob >= 0.3).astype(int)
auc = roc_auc_score(y_test, y_pred_prob)
print("AUC-ROC Score:", auc)

AUC-ROC Score: 0.7528095180917287

In [54]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred_custom))

[[30545 14625]
 [ 1791  4109]]
              precision    recall  f1-score   support

           0       0.97      0.34      0.50     45170
           1       0.15      0.92      0.26      5900

    accuracy                           0.40     51070
   macro avg       0.56      0.63      0.38     51070
weighted avg       0.87      0.40      0.47     51070

In [55]:
DATA_PATH = "../data/raw/Loan_Default.csv"   # change path if needed
df = pd.read_csv(DATA_PATH)
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# Preprocessing

In [56]:
df.to_csv("Loan_Default_Cleaned.csv", index=False)

In [57]:
import pandas as pd
import numpy as np
df = pd.read_csv("Loan_Default_Cleaned.csv")

In [58]:
df.drop_duplicates(inplace=True)

In [62]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner',
       'Default'],
      dtype='object')

In [63]:
if 'ID' in df.columns:
    df.drop(['ID'], axis=1, inplace=True)

In [60]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].astype(str).str.strip().str.lower()

In [65]:
df['DTIRatio'] = df['DTIRatio'].fillna(df['DTIRatio'].median())

In [66]:
df['CreditScore'] = df['CreditScore'].fillna(df['CreditScore'].quantile(0.25))

In [67]:
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].median())

In [68]:
for col in df.select_dtypes(include='object'):
    df[col] = df[col].fillna(df[col].mode()[0])

In [69]:
if df['Default'].isna().sum() > 0:
    df['Default'] = df['Default'].fillna('very_poor')

In [71]:
if 'Age' in df.columns:

    age_map = {
        '18-24': 1, '25-34': 2, '35-44': 3,
        '45-54': 4, '55-64': 5, '65-74': 6,
        '65+': 6, '75+': 6, '70+': 6
    }

    df['age_group'] = df['Age'].map(age_map)

    if df['age_group'].dropna().shape[0] > 0:
        df['age_group'] = df['age_group'].fillna(df['age_group'].median())
    else:
        df['age_group'] = df['age_group'].fillna(3)

In [72]:
from sklearn.preprocessing import LabelEncoder

In [73]:
label_cols = df.select_dtypes(include='object').columns
le = LabelEncoder()

In [74]:
for col in label_cols:
    df[col] = le.fit_transform(df[col].astype(str))

In [75]:
from sklearn.preprocessing import StandardScaler

In [76]:
num_cols = df.select_dtypes(include=np.number).columns.drop(['Default']) 
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [77]:
df.to_csv("Loan_Default_Preprocessed.csv", index=False)

In [78]:
print(df.isna().sum())

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
age_group         0
dtype: int64