In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [48]:
df = pd.read_csv("../data/raw/Loan_Default.csv")
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [57]:
# Fill missing values
df = df.fillna(df.median(numeric_only=True))
df = df.fillna(df.mode().iloc[0])

# Ensure target column is integer
cols_to_int = ['Default','HasMortgage','HasDependents','HasCoSigner']
for col in cols_to_int:
    try:
        df[col] = df[col].astype(int)
    except:
        df[col] = df[col].map({'Yes': 1, 'No': 0})

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  int64
 14  HasDependents   255347 non-null  int64
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  int64
 17  Default         255347 non-null  int64
dtypes: float64(2), int64(11), object(5)
memory usage: 35.1+ MB

In [59]:
cat_cols=df.select_dtypes(include=['object']).columns
cat_cols=cat_cols.drop(['Default','LoanID'],errors='ignore')
cat_cols

Index(['Education', 'EmploymentType', 'MaritalStatus', 'LoanPurpose'], dtype='object')

In [60]:
for col in cat_cols:
    print(col, df[col].unique())

Education ["Bachelor's" "Master's" 'High School' 'PhD']
EmploymentType ['Full-time' 'Unemployed' 'Self-employed' 'Part-time']
MaritalStatus ['Divorced' 'Married' 'Single']
LoanPurpose ['Other' 'Auto' 'Business' 'Home' 'Education']

In [61]:
df = pd.get_dummies(df, columns=cat_cols)
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,...,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Auto,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,...,False,False,True,False,False,False,False,False,False,True
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,...,False,False,False,True,False,False,False,False,False,True
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,...,False,True,True,False,False,True,False,False,False,False
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,...,False,False,False,True,False,False,True,False,False,False
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,...,False,True,True,False,False,True,False,False,False,False

In [62]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'HasMortgage', 'HasDependents', 'HasCoSigner', 'Default',
       'Education_Bachelor's', 'Education_High School', 'Education_Master's',
       'Education_PhD', 'EmploymentType_Full-time', 'EmploymentType_Part-time',
       'EmploymentType_Self-employed', 'EmploymentType_Unemployed',
       'MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'LoanPurpose_Auto', 'LoanPurpose_Business',
       'LoanPurpose_Education', 'LoanPurpose_Home', 'LoanPurpose_Other'],
      dtype='object')

In [63]:
y_col = 'Default'

cols_to_ignore = ['LoanID']

x_cols = [col for col in df.columns if col not in cols_to_ignore+[y_col]]
x = df[x_cols]
y = df[y_col]

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [69]:
y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(Default
 0    0.883873
 1    0.116127
 Name: proportion, dtype: float64,
 Default
 0    0.883865
 1    0.116135
 Name: proportion, dtype: float64)

In [71]:
from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression model
log_reg = LogisticRegression(
    random_state=42,
    max_iter = 1000
)

# Train the model
log_reg.fit(x_train, y_train)

# Predict probability for positive class (class = 1)
y_pred_lr = log_reg.predict_proba(x_test)[:, 1]

# Calculate AUC-ROC score
auc_lr = roc_auc_score(y_test, y_pred_lr)

print("Logistic Regression AUC-ROC:", auc_lr)

Logistic Regression AUC-ROC: 0.7521465841873272

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [72]:
xgb = XGBClassifier(eval_metric="logloss")

xgb.fit(x_train, y_train)
y_pred_xgb = xgb.predict_proba(x_test)[:,1]

auc_xgb = roc_auc_score(y_test, y_pred_xgb)
print("XGBoost AUC-ROC:", auc_xgb)

XGBoost AUC-ROC: 0.7431500866640566

In [ ]:
xgb_param_grid = {
    'n_estimators': [100, 200, 500],
    'max_depth': [0, 5, 10],
    'learning_rate': [0.01, 0.1]
}

grid_xgb = GridSearchCV(
    estimator=XGBClassifier(eval_metric="logloss"),
    param_grid=xgb_param_grid,
    scoring='roc_auc',
    cv=3,
    n_jobs=-1
)

grid_xgb.fit(x_train, y_train)

print("Best XGBoost Params:", grid_xgb.best_params_)
print("Best XGBoost AUC:", grid_xgb.best_score_)

Best XGBoost Params: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
Best XGBoost AUC: 0.7529604894178505

In [75]:
lgbm = LGBMClassifier()

lgbm.fit(x_train, y_train)
y_pred_lgbm = lgbm.predict_proba(x_test)[:,1]

auc_lgbm = roc_auc_score(y_test, y_pred_lgbm)
print("LightGBM AUC-ROC:", auc_lgbm)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 23722, number of negative: 180555
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.021263 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1323
[LightGBM] [Info] Number of data points in the train set: 204277, number of used features: 28
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116127 -> initscore=-2.029633
[LightGBM] [Info] Start training from score -2.029633
LightGBM AUC-ROC: 0.7572955422144982

In [76]:
lgbm_param_grid = {
    'n_estimators': [100, 200, 500],
    'max_depth': [-1, 5, 10],
    'learning_rate': [0.001, 0.01, 0.1]
}

grid_lgbm = GridSearchCV(
    estimator=LGBMClassifier(),
    param_grid=lgbm_param_grid,
    scoring='roc_auc',
    cv=3,
    n_jobs=-1
)

grid_lgbm.fit(x_train, y_train)

print("Best LightGBM Params:", grid_lgbm.best_params_)
print("Best LightGBM AUC:", grid_lgbm.best_score_)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 23722, number of negative: 180555
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018370 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1323
[LightGBM] [Info] Number of data points in the train set: 204277, number of used features: 28
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.116127 -> initscore=-2.029633
[LightGBM] [Info] Start training from score -2.029633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Best LightGBM Params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
Best LightGBM AUC: 0.7515594196550531

In [77]:
print("Baseline Logistic Regression AUC:", auc_lr)
print("XGBoost AUC:", auc_xgb)
print("LightGBM AUC:", auc_lgbm)

print("\nBest Tuned XGBoost AUC:", grid_xgb.best_score_)
print("Best Tuned LightGBM AUC:", grid_lgbm.best_score_)

Baseline Logistic Regression AUC: 0.7521465841873272
XGBoost AUC: 0.7431500866640566
LightGBM AUC: 0.7572955422144982

Best Tuned XGBoost AUC: 0.7529604894178505
Best Tuned LightGBM AUC: 0.7515594196550531

In [31]:
# save the model to disk
import joblib
filename = 'best_model.sav'
joblib.dump(lgbm, filename)

['best_model.sav']

In [32]:
# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(x_test, y_test)
print(result)

1.0